In [291]:
import numpy as np
import pandas as pd

# Exercises 1

## 1

Combinations of two dice that add to a given number:

In [292]:
die = np.arange(1, 7)
dice = np.tile(die, (6, 1))
dice = pd.DataFrame(dice + dice.transpose(), columns=die, index=die)
dice

1  2  3   4   5   6
1  2  3  4   5   6   7
2  3  4  5   6   7   8
3  4  5  6   7   8   9
4  5  6  7   8   9  10
5  6  7  8   9  10  11
6  7  8  9  10  11  12

In [293]:
n_10 = (dice == 10).values.sum()
n_10

3

In [294]:
n_11 = (dice == 11).values.sum()
n_11

2

### a)

Prior probability of craps and roulette:

In [295]:
prior = np.array([1, 2])
prior = prior / prior.sum()
prior

array([0.33333333, 0.66666667])

Likelihood for craps and roulette:

In [296]:
likelihood = np.array([n_11/18, 1/38])
likelihood

array([0.11111111, 0.02631579])

Posterior probability for craps and roulette:

In [297]:
posterior = prior * likelihood
posterior = posterior / posterior.sum()
posterior

array([0.67857143, 0.32142857])

In [298]:
posterior[0].round(2)

0.68

### b)

Prior probability of craps and roulette:

In [299]:
prior = np.array([2, 1])
prior = prior / prior.sum()
prior

array([0.66666667, 0.33333333])

Likelihood for craps and roulette:

In [300]:
likelihood = np.array([n_10/18, 1/38])
likelihood

array([0.16666667, 0.02631579])

Posterior probability for craps and roulette:

In [301]:
posterior = prior * likelihood
posterior = posterior / posterior.sum()
posterior

array([0.92682927, 0.07317073])

In [302]:
posterior[1].round(2)

0.07

## 2

Assuming you pick door 1 and the host opens door 3, the prior probabilities are following:

In [303]:
prior = np.ones(3) / 3
prior

array([0.33333333, 0.33333333, 0.33333333])

Likelihood counts the ways the car can have ended up behind doors 1 and 2 given that door 3 has a goat.

In [304]:
likelihood = np.array([1, 2, 0])

Probabilities for each door are:

In [305]:
posterior = prior * likelihood
posterior = posterior / posterior.sum()
posterior.round(2)

array([0.33, 0.67, 0.  ])

Door 2 has higher posterior probability, so the contestant should always switch. This can be explained by the fact that the
host always gives the contestant new and reliable information on the game setup. The contestant should update their beliefs
because they always have more information when choosing between the doors after the goat reveal than before it.

## 3

In [306]:
fruits = pd.DataFrame(
    [[3, 4, 3],
    [1, 1, 0],
    [3, 3, 4]],
    columns=['apples', 'oranges', 'limes'],
    index=['r', 'b', 'g'],
)
p_box = pd.Series(dict(r=0.2, b=0.2, g=0.6))
fruits_p = fruits / fruits.values.sum(axis=1, keepdims=True)
fruits_p

apples  oranges  limes
r     0.3      0.4    0.3
b     0.5      0.5    0.0
g     0.3      0.3    0.4

### a)

In [307]:
combined_p = fruits_p * np.tile(p_box.values[..., np.newaxis], (1, 3))
combined_p.apples.sum().round(2)

0.34

Probability of an apple is 1/3.

### b)

In [308]:
prior = p_box.values
likelihood = fruits_p.oranges.values
posterior = prior * likelihood
posterior = posterior / posterior.sum()
posterior[1].round(2)

0.28

## 4

## 5